logging:
  pattern:
    console: "%d{HH:mm:ss yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.workswap.config.SecurityConfig: INFO
    org.workswap.config.WebSocketConfig: INFO

    org.workswap.api.controller.ChatController: INFO  
    org.workswap.api.controller.ChatWebSocketController: INFO

    org.workswap.api.controller.UploadController: INFO
    org.workswap.api.controller.AuthController: INFO
    
    org.workswap.core.services.UserService: INFO
    org.workswap.core.services.ChatService: INFO
    org.workswap.core.services.CategoryService: INFO
    org.workswap.core.services.StatService: INFO
    org.workswap.core.services.LocalizationService: INFO
    org.workswap.core.services.NotificationService: INFO 
    org.workswap.core.services.ReviewService: INFO

    org.workswap.core.services.query.ListingQueryService: INFO
    org.workswap.core.services.command.PermissionCommandSevice: INFO
    
    org.workswap.core.services.components.AuthService: INFO
    org.workswap.core.services.components.LangFileScheduler: INFO

    org.workswap.core.services.components.security.authentication.CustomOAuth2SuccessHandler: INFO
    org.workswap.core.services.components.security.authentication.CustomOAuth2FailureHandler: INFO
    org.workswap.core.services.components.security.AuthChannelInterceptor: INFO
    org.workswap.core.services.components.security.JwtTokenConverter: INFO

    org.springframework.web.multipart: INFO
    org.springframework.web.servlet.resource: INFO
    org.springframework.security: INFO

    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO