spring:
  profiles:
    active: 
      - "api"
      - "production"
      - "backoffice"
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MariaDBDialect

api:
  url: http://localhost:8083 #https://api.workswap.org
  key:
    localization: 9gxqzuZo8EmYopc5MF43

frontend:
  url: http://localhost:30000 #https://workswap.org

cloud:
  url: https://cloud.workswap.org #http://localhost:8084

app:
  cookie:
    secure: false
    domain: "localhost" # ".workswap.org"
    sameSite: "Strict"

tgbot:
  url: http://89.35.130.223:30003

isTest: true

salavion: 
  url: http://localhost:8001
  code: f9wh9023r023g7d3

mailjet:
  api-key: 7f3bda3c5576d2b30b363c3b8f983c8d
  secret-key: 535c970b6cecc2652d3e107789d0e4f4
  sender: kkodolov40@gmail.com