spring:
  config:
    import:
      - classpath:config/oauth.yml
      - classpath:config/database.yml
      - classpath:config/main.yml
      - classpath:config/logging.yml
      - classpath:config/cors.yml
      - classpath:config/rabbitmq.yml
      - optional:file:./config-dev/oauth.yml
      - optional:file:./config-dev/database.yml
      - optional:file:./config-dev/main.yml
      - optional:file:./config-dev/logging.yml
      - optional:file:./config-dev/cors.yml
      - optional:file:./config-dev/rabbitmq.yml