spring:
  config:
    import:
      - classpath:config/oauth.yml
      - classpath:config/database.yml
      - classpath:config/main.yml
      - classpath:config/logging.yml
      - classpath:config/cors.yml
      - optional:file:./config/oauth.yml
      - optional:file:./config/database.yml
      - optional:file:./config/main.yml
      - optional:file:./config/logging.yml
      - optional:file:./config/cors.yml